import type { TeamMember } from '../types/TeamPage.types'

export const feedbackTeamMembers: TeamMember[] = [
  {
    empNo: '1',
    empName: '이혜수',
    profileImage: '👨‍💼',
    position: 'AI Engineer',
    contributionRate: 95,
    skill: '우수',
    attitude: '매우 우수',
    ranking: 1,
  },
  {
    empNo: '2',
    empName: '신택수',
    profileImage: '👨‍💻',
    position: 'BE Engineer',
    contributionRate: 88,
    skill: '우수',
    attitude: '매우 우수',
    ranking: 2,
  },
  {
    empNo: '3',
    empName: '김재현',
    profileImage: '👨‍💼',
    position: 'BE Engineer',
    contributionRate: 80,
    skill: '보통',
    attitude: '우수',
    ranking: 3,
  },
  {
    empNo: '4',
    empName: '이지선',
    profileImage: '👩‍💻',
    position: 'AI Engineer',
    contributionRate: 90,
    skill: '보통',
    attitude: '우수',
    ranking: 4,
  },
  {
    empNo: '5',
    empName: '손지영',
    profileImage: '👩‍💼',
    position: 'PM Manager',
    contributionRate: 82,
    skill: '보통',
    attitude: '우수',
    ranking: 5,
  },
  {
    empNo: '6',
    empName: '조은정',
    profileImage: '👩‍💻',
    position: 'FE Engineer',
    contributionRate: 77,
    skill: '미흡',
    attitude: '우수',
    ranking: 6,
  },
  {
    empNo: '7',
    empName: '박지훈',
    profileImage: '👨‍💻',
    position: 'FE Engineer',
    contributionRate: 75,
    skill: '미흡',
    attitude: '우수',
    ranking: 7,
  },
  {
    empNo: '8',
    empName: '최민수',
    profileImage: '👨‍🎨',
    position: 'Designer',
    contributionRate: 70,
    skill: '미흡',
    attitude: '보통',
    ranking: 8,
  },
  {
    empNo: '9',
    empName: '이수진',
    profileImage: '👩‍🎨',
    position: 'Designer',
    contributionRate: 68,
    skill: '미흡',
    attitude: '보통',
    ranking: 9,
  },
  {
    empNo: '10',
    empName: '김영수',
    profileImage: '👨‍🔧',
    position: 'QA Engineer',
    contributionRate: 65,
    skill: '미흡',
    attitude: '미흡',
    ranking: 10,
  },
  {
    empNo: '11',
    empName: '박지영',
    profileImage: '👩‍🔧',
    position: 'QA Engineer',
    contributionRate: 60,
    skill: '미흡',
    attitude: '미흡',
    ranking: 11,
  },
  {
    empNo: '12',
    empName: '정우성',
    profileImage: '👨‍💻',
    position: 'DevOps Engineer',
    contributionRate: 55,
    skill: '미흡',
    attitude: '미흡',
    ranking: 12,
  },
  {
    empNo: '13',
    empName: '이민호',
    profileImage: '👨‍🔬',
    position: 'Data Scientist',
    contributionRate: 50,
    skill: '미흡',
    attitude: '미흡',
    ranking: 13,
  },
  {
    empNo: '14',
    empName: '김하늘',
    profileImage: '👩‍🔬',
    position: 'Data Analyst',
    contributionRate: 45,
    skill: '미흡',
    attitude: '미흡',
    ranking: 14,
  },
  {
    empNo: '15',
    empName: '최지우',
    profileImage: '👨‍💻',
    position: 'System Architect',
    contributionRate: 40,
    skill: '미흡',
    attitude: '미흡',
    ranking: 15,
  },
  {
    empNo: '16',
    empName: '박서준',
    profileImage: '👨‍💻',
    position: 'Network Engineer',
    contributionRate: 35,
    skill: '미흡',
    attitude: '미흡',
    ranking: 16,
  },
]

export const fianlTeamMembers = [
  {
    empNo: '1',
    empName: '이혜수',
    profileImage: '👨‍💼',
    position: 'AI Engineer',
    contributionRate: 95,
    skill: '우수',
    score: 4.8,
    ranking: 1,
  },
  {
    empNo: '2',
    empName: '신택수',
    profileImage: '👨‍💻',
    position: 'BE Engineer',
    contributionRate: 88,
    skill: '우수',
    score: 3.8,
    ranking: 2,
  },
  {
    empNo: '3',
    empName: '김재현',
    profileImage: '👨‍💼',
    position: 'BE Engineer',
    contributionRate: 80,
    skill: '보통',
    score: 3.5,
    ranking: 3,
  },
  {
    empNo: '4',
    empName: '이지선',
    profileImage: '👩‍💻',
    position: 'AI Engineer',
    contributionRate: 90,
    skill: '보통',
    score: 4.0,
    ranking: 4,
  },
  {
    empNo: '5',
    empName: '손지영',
    profileImage: '👩‍💼',
    position: 'PM Manager',
    contributionRate: 82,
    skill: '보통',
    score: 3.6,
    ranking: 5,
  },
  {
    empNo: '6',
    empName: '조은정',
    profileImage: '👩‍💻',
    position: 'FE Engineer',
    contributionRate: 77,
    skill: '미흡',
    score: 3.0,
    ranking: 6,
  },
  {
    empNo: '7',
    empName: '박지훈',
    profileImage: '👨‍💻',
    position: 'FE Engineer',
    contributionRate: 75,
    skill: '미흡',
    score: 2.8,
    ranking: 7,
  },
  {
    empNo: '8',
    empName: '최민수',
    profileImage: '👨‍🎨',
    position: 'Designer',
    contributionRate: 70,
    skill: '미흡',
    score: 2.5,
    ranking: 8,
  },
  {
    empNo: '9',
    empName: '이수진',
    profileImage: '👩‍🎨',
    position: 'Designer',
    contributionRate: 68,
    skill: '미흡',
    score: 2.3,
    ranking: 9,
  },
  {
    empNo: '10',
    empName: '김영수',
    profileImage: '👨‍🔧',
    position: 'QA Engineer',
    contributionRate: 65,
    skill: '미흡',
    score: 2.0,
    ranking: 10,
  },
  {
    empNo: '11',
    empName: '박지영',
    profileImage: '👩‍🔧',
    position: 'QA Engineer',
    contributionRate: 60,
    skill: '미흡',
    score: 1.8,
    ranking: 11,
  },
  {
    empNo: '12',
    empName: '정우성',
    profileImage: '👨‍💻',
    position: 'DevOps Engineer',
    contributionRate: 55,
    skill: '미흡',
    score: 1.5,
    ranking: 12,
  },
  {
    empNo: '13',
    empName: '이민호',
    profileImage: '👨‍🔬',
    position: 'Data Scientist',
    contributionRate: 50,
    skill: '미흡',
    score: 1.2,
    ranking: 13,
  },
  {
    empNo: '14',
    empName: '김하늘',
    profileImage: '👩‍🔬',
    position: 'Data Analyst',
    contributionRate: 45,
    skill: '미흡',
    score: 1.0,
    ranking: 14,
  },
  {
    empNo: '15',
    empName: '최지우',
    profileImage: '👨‍💻',
    position: 'System Architect',
    contributionRate: 40,
    skill: '미흡',
    score: 0.8,
    ranking: 15,
  },
  {
    empNo: '16',
    empName: '박서준',
    profileImage: '👨‍💻',
    position: 'Network Engineer',
    contributionRate: 35,
    skill: '미흡',
    score: 0.5,
    ranking: 16,
  },
]
